### ISSUE TITLE
Support status

### ISSUE THREAD

**Issue by msama** [mttkay/calculon#4]
Mattias,

I have to decide whether to start using Calculon or not.
Are you still maintaining/supporting it?

Thanks,
Michele

**Comment by futtetennista** [comment]
Hey Michele,

Simple answer is: no. We stopped working at this a while ago because we found the Android test framework to be too flaky. We wanted to have another look at it at some point to check if any progress was made - especially after the recent changes to Mockito that make it compatible with Dalvik - but it's in our todo list and I cannot tell you when we'll do that.

**Comment by msama** [comment]
Thanks Stefano. 

Given your answer I suppose I will have to think twice before using Calculon.
Please let me know as soon as you restart working on it and if you need an extra help.

**Comment by futtetennista** [comment]
Honestly I'd love to go back working on it, but I want to be sure that that's a good time investment. As I wrote we stopped using Instrumentation tests a while ago, but if you're using them and want to exchange some ideas just drop me an email lines when you've got time (it's in my github profile).
